- name: first demo varibale
  hosts: all
  vars_files:
    - exvars.yml
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}



- name: Demo first playbook
  hosts: all
  roles:
    - first_play
  tasks:
    - name: print role 
      ansible.builtin.debug:
        msg: 