- name: first varibale_files
  hosts: all
  vars_files:
    - exvars.yml
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}

- name: first_variable_on_task_level
  hosts: all
  tasks:
    - name: task_level_variable
      ansible.builtin.debug:
        msg: URL - {{ URL }}
      vars:
        URL: task_level_variable_01


